[package]
name = "llm-ls"
version = "0.2.2"
edition = "2021"

[[bin]]
name = "llm-ls"

[dependencies]
home = "0.5"
ropey = "1.6"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
tokenizers = { version = "0.13", default-features = false, features = ["onig"] }
tokio = { version = "1", features = ["fs", "io-std", "io-util", "macros", "rt-multi-thread"] }
tower-lsp = "0.20"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

