name: test
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  testbed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup default nightly
          rustup update

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Set up repo dependencies cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            /tmp/huggingface_hub-venv/
            /tmp/fastapi-venv/
            /tmp/starlette-venv/
          key: ${{ runner.os }}-deps-${{ hashFiles('crates/testbed/repositories.yaml') }}
          restore-keys: ${{ runner.os }}-deps-${{ hashFiles('crates/testbed/repositories.yaml') }}

      - name: Build project
        run: cargo build

      - name: Run testbed
        run: cargo run --bin testbed -- --api-token $API_TOKEN
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        if: github.event_name == 'pull_request'
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '| Repository name | Source type | Average hole completion time (s) | Pass percentage |'

      - name: Create or update comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: results.md
          edit-mode: replace

