name: test
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  testbed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup default nightly
          rustup update

      - name: Build project
        run: cargo build

      - name: Run testbed
        run: cargo run --bin testbed -- --api-token $API_TOKEN
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        if: github.event_name == 'pull_request'
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '| Repository name | Source type | Pass percentage |'

      - name: Create or update comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: results.md
          edit-mode: replace

